<?php
    //
    // Monitor System
    // Google Drive conector (client application )
    //

    sleep(30);
    drive_connector();

// --------------------------------------------------------

    function drive_connector() {

	include_once "driveLibraryV3.php";

	$work_dir = "/var/www/work/";
	$home_dir = "/var/www/html/monitorSystem/";

	openlog("drive_connector", LOG_ODELAY | LOG_PERROR, LOG_USER);

	try {

	    if (($service = GD_createService()) == NULL) {
		syslog(LOG_ERR, "Cannot craete google drive service.");
		return 5;
	    }

	    include($home_dir.'execRemoteCommand.php');
	    ExecRemoteCmd($service);

//	    include($home_dir.'uploadFiles.php');
//	    uploadFiles($service);

	    //
	    // Clean up old image files in the work directory which are generated by CaptureImage module.
	    // Since CaptureImage module may be running in a remote node, clean up is done here alternatively.
	    //
            if (file_exists($work_dir."imageinfo.txt")) {
		//
		// load imageinf.txt file
		//
		$handle = fopen($work_dir."imageinfo.txt", "r");

		while (($line = fgets($handle, 1024)) != FALSE) {
		    $key = strtok($line, "=\n");
		    $value = strtok("=\n");
		    if ($key == 'filename') {
			$linkName = $value;
			break;
		    }
        	}

        	fclose($handle);
	    }

	    foreach (glob($work_dir."ccam_*.jpg") as $tmpfile) {
		if (basename($tmpfile) != $linkName) unlink($tmpfile);
	    }

	} catch (Exception $e) {
	    syslog(LOG_ERR, $e->getMessage());
	}
    }
 ?>
